version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: association-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: association_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
