import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FamEase",
  authors: [{ name: "FamEase" }],
  creator: "FamEase",
  keywords: [
    "FamEase",
    "Famille",
    "Gestion",
    "Suivi",
    "Trésorerie",
    "Excel",
    "Import",
    "Export",
    "Facture",
    "Paiement",
    "Gestion de famille",
    "Gestion de trésorerie",
    "Gestion de cotisation",
    "Gestion de facture",
    "Gestion de paiement",
    "Gestion de famille",
    "Gestion de trésorerie",
    "Gestion de cotisation",
    "Gestion de facture",
    "Gestion de paiement",
  ],
  description: "Generated by create next app",
  icons: {
    icon: "/Favicon.ico",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme='fantasy'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
